 export const GET_SWIPER_DATA = "getSwiperData"
 export const GET_ICON_DATA = "getIconData"
 export const GET_SHOPLIST_DATA = "getShopListData"
 export const GET_RECOMMENDED_DATA = "getRecommendedData"
 export const GET_SEARCHLIST_DATA = "getsearchListData"
